### ISSUE TITLE
XCode 11 support ? 

### ISSUE THREAD

**Issue by jcbernabe1492** [tsolomko/BitByteData#3]
Hi , 

Will there be a release that will support XCode 11? Right now I'm pointing my cartfile in SWCompression to "develop" just to get the latest codebase that was build with swift 5.x 

Thanks!

**Comment by tsolomko** [comment]
Thank you for your feedback. I will release an update with the changes to support Xcode 11/Swift 5.x very soon (hopefully, either today or tomorrow). I will also post a more detailed response about this problem to your issue on SWCompression repository.

**Comment by jcbernabe1492** [comment]
Thanks for the quick response. Great to hear that, we just really needed this due to the upcoming app store restriction on April that all apps must be built with Xcode 11. Thanks a lot!
