### ISSUE TITLE
uint32() -> UInt32 crash due to range overflow on v.2.0.1

### ISSUE THREAD

**Issue by Tarasus** [tsolomko/BitByteData#8]
Not sure if necessary, got this crash on v.2.0.1 

```
Thread 0#0	(null) in Data._Representation.subscript.getter ()
#1	(null) in Data.subscript.getter ()
#2	0x0000000102e30ee0 in LittleEndianByteReader.uint32() at /SourcePackages/checkouts/BitByteData/Sources/LittleEndianByteReader.swift:84
#3	0x0000000102e24fe8 in specialized static ZipContainer.infoWithHelper(_:) at /SourcePackages/checkouts/SWCompression/Sources/ZIP/ZipContainer.swift:172
#4	(null) in static ZipContainer.infoWithHelper(_:) ()
#5	0x0000000102e25f00 in specialized static ZipContainer.info(container:) at /SourcePackages/checkouts/SWCompression/Sources/ZIP/ZipContainer.swift:140
#6	(null) in static ZipContainer.info(container:) ()
#7	0x0000000102ab9b94 in specialized processZipToDb(_:) <<--My project entry point
```

As I understand, `public func uint32() -> UInt32` had not enough bytes to read and crashed, and it lacked available range checks.

**Comment by tsolomko** [comment]
@Tarasus,

In addition to my answer to your issue in SWCompression repository, let me quote the documentation of the BitByteData's function that you are using:

```swift
/**
     Reads 4 bytes and returns them as a `UInt32` number, advancing by 4 positions.

     - Precondition: There must be enough bytes left.
*/
```

The precondition part means that it is a responsibility of the user (you) to ensure that there are at least 4 bytes left (by checking, for instance, the `bytesLeft` property) before calling this function.

**Comment by Tarasus** [comment]
The source archive is unknown, I only have a crash report on it. Thank you!
